# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03be4275ea3b07bfe54bb61689d8a37ec311803898d624f2a4438e957bbfd4653dcbd50cbe205f8a201ac662fc0818286677f569025b6ace64738e6b82eeb7d2

test:
  secret_key_base: 7b1be36565425af9ce09c47f26f429733f23fe7debabafd489af9f0946530e7de9d7c46fe3ebb714c551b74c2b1358a49864209cfa782b1532ee204496d8b851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
